stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/maven:3.6-openjdk-17-slim
      shellScript: |-
        LOG_TAG="CHIP-INFO"
        ls -l
        echo "[$LOG_TAG]===========Execute Maven CMD Build Project Start==========="
        mvn clean package -Dmaven.test.skip=true
        echo "[$LOG_TAG]===========Execute Maven CMD Build Project End==========="
        echo "[$LOG_TAG]Dir:target ls -l:`pwd`"
        ls -l ./game-server-manager-server/target
    when:
      event: {}
- name: 推送server镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./game-server-manager-server/Dockerfile-Rancher
      buildContext: .
      tag: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager:server-1.0.0
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
    when:
      event: {}
- name: 推送uc镜像
  steps:
    - publishImageConfig:
        dockerfilePath: ./game-server-manager-uc/Dockerfile-Rancher
        buildContext: .
        tag: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager:uc-1.0.0
        pushRemote: true
        registry: registry.cn-hangzhou.aliyuncs.com
      when:
        event: {}
- name: 推送generate镜像
  steps:
    - publishImageConfig:
        dockerfilePath: ./game-server-manager-generate/Dockerfile-Rancher
        buildContext: .
        tag: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager:generate-1.0.0
        pushRemote: true
        registry: registry.cn-hangzhou.aliyuncs.com
      when:
        event: {}
- name: 推送plugins镜像
  steps:
    - publishImageConfig:
        dockerfilePath: ./game-server-manager-plugins/Dockerfile-Rancher
        buildContext: .
        tag: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager:plugins-1.0.0
        pushRemote: true
        registry: registry.cn-hangzhou.aliyuncs.com
      when:
        event: {}
- name: 构建前端静态文件
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/node:16.16.0
      shellScript: |-
        cd ./easy-push
        yarn install --registry=https://registry.npmmirror.com
        yarn run build
    when:
      event: {}
- name: 推送前端镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./easy-push/docker/Dockerfile-Rancher
      buildContext: .
      tag: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager:web-1.0.0
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
    when:
      event: {}
timeout: 60
branch: {}
notification:
  recipients:
  - recipient: rancher流水线通知
    notifier: local:n-d4vwp
  condition:
  - Success
  - Changed
  - Failed
