server:
  port: 9999

spring:
  application:
    name: game-server-manager-plugins
#  data:
#    mongodb:
#      uri: mongodb://${MONGO_DB}/grasscutter


manager-url: ${MANAGER_URL:https://manager.easydo.plus}
application-id: ${APPLICATION_ID}
app-id: ${APP_ID}
app-version: ${APP_VERSION}
