apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    field.cattle.io/creatorId: user-v7bm2
    field.cattle.io/publicEndpoints: '[{"nodeName":"local:machine-p5pwb","addresses":["10.0.8.16"],"port":81,"protocol":"TCP","podName":"server:nginx-proxy-manager-644f46c869-269xl","allNodes":false},{"nodeName":"local:machine-p5pwb","addresses":["10.0.8.16"],"port":80,"protocol":"TCP","podName":"server:nginx-proxy-manager-644f46c869-269xl","allNodes":false},{"nodeName":"local:machine-p5pwb","addresses":["10.0.8.16"],"port":443,"protocol":"TCP","podName":"server:nginx-proxy-manager-644f46c869-269xl","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"8","field.cattle.io/creatorId":"user-v7bm2","field.cattle.io/publicEndpoints":"[{\"nodeName\":\"local:machine-c7b7b\",\"addresses\":[\"10.0.8.16\"],\"port\":80,\"protocol\":\"TCP\",\"podName\":\"server:nginx-proxy-manager-5cb9b94b85-74gnv\",\"allNodes\":false},{\"nodeName\":\"local:machine-c7b7b\",\"addresses\":[\"10.0.8.16\"],\"port\":81,\"protocol\":\"TCP\",\"podName\":\"server:nginx-proxy-manager-5cb9b94b85-74gnv\",\"allNodes\":false},{\"nodeName\":\"local:machine-c7b7b\",\"addresses\":[\"10.0.8.16\"],\"port\":443,\"protocol\":\"TCP\",\"podName\":\"server:nginx-proxy-manager-5cb9b94b85-74gnv\",\"allNodes\":false}]"},"creationTimestamp":null,"generation":1,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-server-nginx-proxy-manager"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:field.cattle.io/publicEndpoints":{}}}},"manager":"rancher","operation":"Update","time":"2022-08-27T16:52:55Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:field.cattle.io/creatorId":{}},"f:labels":{".":{},"f:cattle.io/creator":{},"f:workload.user.cattle.io/workloadselector":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:cattle.io/timestamp":{},"f:field.cattle.io/ports":{}},"f:labels":{".":{},"f:workload.user.cattle.io/workloadselector":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"nginx-proxy-manager\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"DB_MYSQL_HOST\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DB_MYSQL_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DB_MYSQL_PASSWORD\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DB_MYSQL_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DB_MYSQL_USER\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":443,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:hostPort":{},"f:name":{},"f:protocol":{}},"k:{\"containerPort\":80,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:hostPort":{},"f:name":{},"f:protocol":{}},"k:{\"containerPort\":81,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:hostPort":{},"f:name":{},"f:protocol":{}}},"f:resources":{},"f:securityContext":{".":{},"f:allowPrivilegeEscalation":{},"f:capabilities":{},"f:privileged":{},"f:readOnlyRootFilesystem":{},"f:runAsNonRoot":{}},"f:stdin":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:tty":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/data\"}":{".":{},"f:mountPath":{},"f:name":{},"f:subPath":{}},"k:{\"mountPath\":\"/etc/letsencrypt\"}":{".":{},"f:mountPath":{},"f:name":{},"f:subPath":{}}}}},"f:dnsConfig":{},"f:dnsPolicy":{},"f:hostNetwork":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"vol1\"}":{".":{},"f:name":{},"f:persistentVolumeClaim":{".":{},"f:claimName":{}}}}}}}},"manager":"Go-http-client","operation":"Update","time":"2022-08-27T17:02:52Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-08-27T17:43:38Z"}],"name":"nginx-proxy-manager","namespace":"server"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-server-nginx-proxy-manager"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2022-08-27T17:43:34Z","field.cattle.io/ports":"[[{\"containerPort\":80,\"dnsName\":\"nginx-proxy-manager-nodeport\",\"hostPort\":0,\"kind\":\"NodePort\",\"name\":\"80tcp801\",\"protocol\":\"TCP\",\"sourcePort\":80},{\"containerPort\":81,\"dnsName\":\"nginx-proxy-manager-nodeport\",\"hostPort\":0,\"kind\":\"NodePort\",\"name\":\"81tcp811\",\"protocol\":\"TCP\",\"sourcePort\":81},{\"containerPort\":443,\"dnsName\":\"nginx-proxy-manager-nodeport\",\"hostPort\":0,\"kind\":\"NodePort\",\"name\":\"443tcp4431\",\"protocol\":\"TCP\",\"sourcePort\":443}]]"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-server-nginx-proxy-manager"}},"spec":{"containers":[{"env":[{"name":"DB_MYSQL_HOST","value":"npm-mariadb.server"},{"name":"DB_MYSQL_NAME","value":"npm"},{"name":"DB_MYSQL_PASSWORD","value":"npm"},{"name":"DB_MYSQL_PORT","value":"3306"},{"name":"DB_MYSQL_USER","value":"npm"}],"image":"jc21/nginx-proxy-manager:latest","imagePullPolicy":"IfNotPresent","name":"nginx-proxy-manager","ports":[{"containerPort":80,"hostPort":80,"name":"80tcp801","protocol":"TCP"},{"containerPort":81,"hostPort":81,"name":"81tcp811","protocol":"TCP"},{"containerPort":443,"hostPort":443,"name":"443tcp4431","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":true,"capabilities":{},"privileged":true,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true,"volumeMounts":[{"mountPath":"/etc/letsencrypt","name":"vol1","subPath":"npm/letsencrypt"},{"mountPath":"/data","name":"vol1","subPath":"npm/data"}]}],"dnsConfig":{},"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"vol1","persistentVolumeClaim":{"claimName":"data"}}]}}},"status":{}}'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-server-nginx-proxy-manager
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:field.cattle.io/ports: {}
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"nginx-proxy-manager"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"DB_MYSQL_HOST"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_MYSQL_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_MYSQL_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_MYSQL_PORT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB_MYSQL_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
                  k:{"mountPath":"/etc/letsencrypt"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsConfig: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"vol1"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-08-27T18:16:10Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2022-08-27T18:16:10Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:replicas: {}
        f:template:
          f:metadata:
            f:annotations:
              f:cattle.io/timestamp: {}
              f:field.cattle.io/ports: {}
          f:spec:
            f:containers:
              k:{"name":"nginx-proxy-manager"}:
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":81,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":443,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
            f:dnsPolicy: {}
            f:hostNetwork: {}
    manager: Go-http-client
    operation: Update
    time: "2022-08-27T19:31:40Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-08-27T19:31:47Z"
  name: nginx-proxy-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-server-nginx-proxy-manager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-08-27T19:31:39Z"
        field.cattle.io/ports: '[[{"containerPort":81,"dnsName":"nginx-proxy-manager-nodeport","hostPort":81,"kind":"NodePort","name":"81tcp811","protocol":"TCP","sourcePort":81},{"containerPort":80,"dnsName":"nginx-proxy-manager-nodeport","hostPort":80,"kind":"NodePort","name":"80tcp801","protocol":"TCP","sourcePort":80},{"containerPort":443,"dnsName":"nginx-proxy-manager-nodeport","hostPort":443,"kind":"NodePort","name":"443tcp4431","protocol":"TCP","sourcePort":443}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-server-nginx-proxy-manager
    spec:
      containers:
      - env:
        - name: DB_MYSQL_HOST
          value: npm-mariadb.server
        - name: DB_MYSQL_NAME
          value: npm
        - name: DB_MYSQL_PASSWORD
          value: npm
        - name: DB_MYSQL_PORT
          value: "3306"
        - name: DB_MYSQL_USER
          value: npm
        image: jc21/nginx-proxy-manager:latest
        imagePullPolicy: IfNotPresent
        name: nginx-proxy-manager
        ports:
        - containerPort: 81
          hostPort: 81
          name: 81tcp811
          protocol: TCP
        - containerPort: 80
          hostPort: 80
          name: 80tcp801
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: 443tcp4431
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: vol1
          subPath: npm/letsencrypt
        - mountPath: /data
          name: vol1
          subPath: npm/data
      dnsConfig: {}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: data
status: {}
