

ribbon:
  okhttp:
    enabled: true
server:
  port: 8888
  tomcat:
    basedir: /home/production/temp
spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uc
          uri: http://game-server-manager-uc.server:8888/**
          predicates:
            - Path=/uc/**
          filters:
            - StripPrefix=1
        - id: server
          uri: http://game-server-manager-server.server:8888/**
          predicates:
            - Path=/server/**
          filters:
            - StripPrefix=1
        - id: gen
          uri: http://game-server-manager-server.server:8888/**
          predicates:
            - Path=/gen/**
          filters:
            - StripPrefix=1
        - id: oss
          uri: http://game-server-manager-server.server:8888/**
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: log-audit
          uri: http://game-server-manager-uc.server:8888/**
          predicates:
            - Path=/log-audit/**
          filters:
            - StripPrefix=1

management:
  server:
    port: 8689
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
