version: '1.0'
name: pipeline-20220904
displayName: pipeline-20220904
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-61d80c0b
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./game-server-manager
        notify: []
        strategy:
          retry: '0'
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT_WEB
            path:
              - ./dist
              - nginx.conf
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-9c9da697
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager
        username: at2627k4r@aliyun.com
        password: Yu5358915200!
        tag: web-1.0.1
        dockerfile: ./easy-push-arco-pro/Dockerfile
        context: ''
        artifacts:
          - ${BUILD_ARTIFACT_WEB}
        isCache: false
        notify: []
        strategy:
          retry: '0'
strategy:
  blocking: true
