version: '1.0'
name: pipeline-20220904
displayName: pipeline-20220904
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-61d80c0b
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - cd easy-push-acro-pro
          - ''
          - '# 执行编译命令'
          - 'yarn install --registry=https://registry.npmmirror.com '
          - yarn run build
        artifacts:
          - name: BUILD_ARTIFACT_WEB
            path:
              - ./build
              - nginx.conf
              - DockerFile
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-9c9da697
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/easy-do-plus
        username: at2627k4r@aliyun.com
        password: Yu5358915200!
        tag: web-1.0.1
        dockerfile: ./easy-push-arco-pro/Dockerfile
        context: ./easy-push-arco-pro
        artifacts:
          - ${BUILD_ARTIFACT_WEB}
        isCache: true
        notify: []
        strategy:
          retry: '0'
strategy:
  blocking: true
