server:
  port: 8888
  #支持http2
  http2:
    enabled: true
  undertow:
    threads:
      #长链数，一直在runnable状态。设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接
      io: 32
      #短链的线程数，目前所有的http请求都是通过此线程处理。阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
      #它的值设置取决于系统线程执行任务的阻塞系数，当业务执行时间在500ms以下时，1000个worker-thread可支持2000+的qps
      worker: 1000
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    # HTTP POST请求最大的大小
    max-http-post-size: 0
  # 对客户端浏览器的请求与响应做压缩
  compression:
    enabled: true
    # mime-types: application/json,application/xml,text/html,text/xml,type/plain
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: ${MAX_FILE_SIZE:1024MB}
      # 设置总上传的文件大小
      max-request-size: ${MAX_REQUEST_SIZE:1024MB}
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0
  application:
    name: ${APPLICATION_NAME:game-server-manager-oss}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql.server}:${MYSQL_PORT:9090}/${MYSQL_DATA_BASE:game-manager}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
  #redis 配置
  redis:
    host: ${REDIS_HOST:redis.server}
    password: ${REDIS_PASSWORD:n2H%yuXZFS}
    port: ${REDIS_PORT:6379}
    database: 5
    timeout: 20000ms
    lettuce:
      pool:
        #连接池大小，默认为8
        max-active: 20
        #最大空闲连接数
        max-idle: 100
        #最小空闲连接数,只有在time-between-eviction-runs设置为正值时才有效
        min-idle: 50
        #获取连接的最大阻塞等待时间(-1表示不限制)
        max-wait: 30s
        #空闲连接检查线程运行周期
        time-between-eviction-runs: 3000ms
      shutdown-timeout: 100ms
oss:
  #minio文件存储
  minio:
    #是否开启 使用@EnableFileStoreServer注解时生效
    enable: true
    #minio地址
    server-address: ${MINIO_SERVER:https://minio.server:9000}
    #账号
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    #密码
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    #默认桶名称
    default-bucket: ${DEFAULT_BUCKET:file-store}
  #本地文件存储
  local:
    #是否开启 使用@EnableFileStoreServer注解时生效
    enable: false
    #默认分组名称
    default-group-name: defaultGroup
    #存储文件的系统绝对路径
    store-path: D:\defaultOss-path\

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v2/api-docs
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: game.server.manager.oss.controller
  # 配置需要生成接口文档的接口路径
  #  paths-to-match: /brand/**,/admin/**
  customize:
    title: 存储服务 API
    description: 存储服务API接口
    version: 1.0.0
    license:
      name: 未设置
      url: https://push.easydo.plus
    externalDocs:
      description: 外部文档
      url: https://push.easydo.plus


# Sa-Token配置
sa-token:
  # jwt秘钥
  jwt-secret-key: ${JWT_SECRET_KEY:123}
  # token 名称 (同时也是cookie名称)
  token-name: token
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  alone-redis:
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: ${REDIS_HOST:redis.server}
    # Redis服务器连接端口
    port: ${REDIS_PORT:6379}
    # Redis服务器连接密码（默认为空）
    password: ${REDIS_PASSWORD:n2H%yuXZFS}
    # 连接超时时间
    timeout: 10s

management:
  server:
    port: 8689
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
