apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-hz94g
    field.cattle.io/publicEndpoints: '[{"port":30000,"protocol":"TCP","serviceName":"server:api-gateway-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-server-api-gateway
  name: api-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-server-api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-02T17:40:18Z"
        field.cattle.io/ports: '[[{"containerPort":8888,"dnsName":"api-gateway-nodeport","hostPort":0,"kind":"NodePort","name":"8888tcp300001","protocol":"TCP","sourcePort":30000},{"containerPort":8888,"dnsName":"api-gateway","hostPort":0,"kind":"ClusterIP","name":"8888tcp2","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-server-api-gateway
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/game-server-manager:gateway-1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8689
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: api-gateway
        ports:
        - containerPort: 8888
          name: 8888tcp300001
          protocol: TCP
        - containerPort: 8888
          name: 8888tcp2
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health
            port: 8689
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
