apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
    field.cattle.io/creatorId: user-mqcd7
    field.cattle.io/publicEndpoints: '[{"port":30002,"protocol":"TCP","serviceName":"server:easy-do-plus-server-nodeport","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2","field.cattle.io/creatorId":"user-mqcd7","field.cattle.io/publicEndpoints":"[{\"port\":32024,\"protocol\":\"TCP\",\"serviceName\":\"server:easy-do-plus-server-nodeport\",\"allNodes\":true}]"},"creationTimestamp":null,"generation":1,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-server-easy-do-plus-server"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:field.cattle.io/creatorId":{}},"f:labels":{".":{},"f:cattle.io/creator":{},"f:workload.user.cattle.io/workloadselector":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:cattle.io/timestamp":{},"f:field.cattle.io/ports":{}},"f:labels":{".":{},"f:workload.user.cattle.io/workloadselector":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"easy-do-plus-server\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"DOMAIN\"}":{".":{},"f:name":{}},"k:{\"name\":\"MYSQL_HOST\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"MYSQL_PASS\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"MYSQL_PORT\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"MYSQL_USER\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"REDIS_HOST\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"REDIS_PORT\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:configMapKeyRef":{"f:key":{},"f:name":{},"f:optional":{}}}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8888,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:securityContext":{".":{},"f:allowPrivilegeEscalation":{},"f:capabilities":{},"f:privileged":{},"f:readOnlyRootFilesystem":{},"f:runAsNonRoot":{}},"f:stdin":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:tty":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/data\"}":{".":{},"f:mountPath":{},"f:name":{},"f:subPath":{}}}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"vol1\"}":{".":{},"f:name":{},"f:persistentVolumeClaim":{".":{},"f:claimName":{}}}}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2022-08-27T15:13:31Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:field.cattle.io/publicEndpoints":{}}}},"manager":"rancher","operation":"Update","time":"2022-08-27T15:13:31Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:replicas":{},"f:template":{"f:metadata":{"f:annotations":{"f:cattle.io/timestamp":{},"f:field.cattle.io/ports":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"easy-do-plus-server\"}":{"f:env":{"k:{\"name\":\"DOMAIN\"}":{"f:value":{}},"k:{\"name\":\"MYSQL_HOST\"}":{"f:valueFrom":{"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"MYSQL_PASS\"}":{"f:valueFrom":{"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"MYSQL_PORT\"}":{"f:valueFrom":{"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"MYSQL_USER\"}":{"f:valueFrom":{"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"REDIS_HOST\"}":{"f:valueFrom":{"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{},"f:optional":{}}}},"k:{\"name\":\"REDIS_PORT\"}":{"f:valueFrom":{"f:configMapKeyRef":{".":{},"f:key":{},"f:name":{},"f:optional":{}}}}},"f:ports":{"k:{\"containerPort\":8888,\"protocol\":\"TCP\"}":{"f:name":{}}}}},"f:volumes":{"k:{\"name\":\"vol1\"}":{"f:persistentVolumeClaim":{"f:claimName":{}}}}}}}},"manager":"Go-http-client","operation":"Update","time":"2022-08-27T15:15:34Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-08-27T16:27:47Z"}],"name":"easy-do-plus-server","namespace":"server"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-server-easy-do-plus-server"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2022-08-27T15:14:36Z","field.cattle.io/ports":"[[{\"containerPort\":8888,\"dnsName\":\"easy-do-plus-server-nodeport\",\"hostPort\":0,\"kind\":\"NodePort\",\"name\":\"8888tcp01\",\"protocol\":\"TCP\",\"sourcePort\":0}]]"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-server-easy-do-plus-server"}},"spec":{"containers":[{"env":[{"name":"DOMAIN","value":"https://push.easydo.plus"},{"name":"MYSQL_HOST","valueFrom":{"configMapKeyRef":{"key":"MYSQL_HOST","name":"mysql","optional":false}}},{"name":"MYSQL_PORT","valueFrom":{"configMapKeyRef":{"key":"MYSQL_PORT","name":"mysql","optional":false}}},{"name":"MYSQL_USER","valueFrom":{"configMapKeyRef":{"key":"MYSQL_USER","name":"mysql","optional":false}}},{"name":"MYSQL_PASS","valueFrom":{"configMapKeyRef":{"key":"MYSQL_PASS","name":"mysql","optional":false}}},{"name":"REDIS_HOST","valueFrom":{"configMapKeyRef":{"key":"REDIS_HOST","name":"redis","optional":false}}},{"name":"REDIS_PORT","valueFrom":{"configMapKeyRef":{"key":"REDIS_PORT","name":"redis","optional":false}}}],"image":"registry.cn-hangzhou.aliyuncs.com/gebilaoyu/easy-do-plus-server:latest","imagePullPolicy":"Always","name":"easy-do-plus-server","ports":[{"containerPort":8888,"name":"8888tcp01","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true,"volumeMounts":[{"mountPath":"/data","name":"vol1","subPath":"game-manager-server"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"vol1","persistentVolumeClaim":{"claimName":"data"}}]}}},"status":{}}'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-server
  name: easy-do-plus-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-02T17:37:49Z"
        field.cattle.io/ports: '[[{"containerPort":8888,"dnsName":"easy-do-plus-server-nodeport","kind":"NodePort","name":"8888tcp300021","protocol":"TCP","sourcePort":30002},{"containerPort":8888,"dnsName":"easy-do-plus-server","kind":"ClusterIP","name":"8888tcp2","protocol":"TCP"}]]'
        field.cattle.io/publicEndpoints: '[{"allNodes":true,"port":30002,"protocol":"TCP","serviceId":"server:easy-do-plus-server-nodeport"}]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-server
    spec:
      containers:
      - env:
        - name: DOMAIN
          value: https://push.easydo.plus
        - name: JAVA_OPTS
          value: --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED
            --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: mysql
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PORT
              name: mysql
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: mysql
        - name: MYSQL_PASS
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASS
              name: mysql
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: redis
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: redis
        image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/easy-do-plus:server-1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8689
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: easy-do-plus-server
        ports:
        - containerPort: 8888
          name: 8888tcp300021
          protocol: TCP
        - containerPort: 8888
          name: 8888tcp2
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health
            port: 8689
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: vol1
          subPath: game-manager-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: data
status: {}
