apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    field.cattle.io/creatorId: user-hz94g
    field.cattle.io/publicEndpoints: '[{"port":30003,"protocol":"TCP","serviceName":"server:easy-do-plus-generate-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-generate
  name: easy-do-plus-generate
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-generate
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-02T17:43:23Z"
        field.cattle.io/ports: '[[{"containerPort":8888,"dnsName":"easy-do-plus-generate-nodeport","hostPort":0,"kind":"NodePort","name":"8888tcp300031","protocol":"TCP","sourcePort":30003},{"containerPort":8888,"dnsName":"easy-do-plus-generate","hostPort":0,"kind":"ClusterIP","name":"8888tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-generate
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED
            --add-opens java.base/java.lang.reflect=ALL-UNNAMED
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: mysql
              optional: false
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PORT
              name: mysql
              optional: false
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: mysql
              optional: false
        - name: MYSQL_PASS
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASS
              name: mysql
              optional: false
        image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/easy-do-plus:generate-1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8689
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: easy-do-plus-generate
        ports:
        - containerPort: 8888
          name: 8888tcp300031
          protocol: TCP
        - containerPort: 8888
          name: 8888tcp02
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health
            port: 8689
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: vol1
          subPath: game-manager-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: data
status: {}
