apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
    field.cattle.io/creatorId: user-mqcd7
    field.cattle.io/publicEndpoints: '[{"port":30010,"protocol":"TCP","serviceName":"server:easy-do-plus-web-nodeport","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3","field.cattle.io/creatorId":"user-mqcd7","field.cattle.io/publicEndpoints":"[{\"port\":30147,\"protocol\":\"TCP\",\"serviceName\":\"server:easy-do-plus-web-nodeport\",\"allNodes\":true}]"},"creationTimestamp":null,"generation":1,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-server-easy-do-plus-web"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:field.cattle.io/creatorId":{}},"f:labels":{".":{},"f:cattle.io/creator":{},"f:workload.user.cattle.io/workloadselector":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:cattle.io/timestamp":{},"f:field.cattle.io/ports":{}},"f:labels":{".":{},"f:workload.user.cattle.io/workloadselector":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"easy-do-plus-web\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:securityContext":{".":{},"f:allowPrivilegeEscalation":{},"f:capabilities":{},"f:privileged":{},"f:readOnlyRootFilesystem":{},"f:runAsNonRoot":{}},"f:stdin":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:tty":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/opt/bitnami/nginx/conf/server_blocks/\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"vol3\"}":{".":{},"f:configMap":{".":{},"f:defaultMode":{},"f:items":{},"f:name":{},"f:optional":{}},"f:name":{}}}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2022-08-27T15:14:48Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:field.cattle.io/publicEndpoints":{}}}},"manager":"rancher","operation":"Update","time":"2022-08-27T15:14:48Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:template":{"f:metadata":{"f:annotations":{"f:cattle.io/timestamp":{},"f:field.cattle.io/ports":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"easy-do-plus-web\"}":{"f:ports":{".":{},"k:{\"containerPort\":8080,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:name":{},"f:protocol":{}}}}}}}}},"manager":"Go-http-client","operation":"Update","time":"2022-08-27T17:05:25Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-08-27T17:05:27Z"}],"name":"easy-do-plus-web","namespace":"server"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-server-easy-do-plus-web"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2022-08-27T17:05:24Z","field.cattle.io/ports":"[[{\"containerPort\":8080,\"dnsName\":\"easy-do-plus-web-nodeport\",\"hostPort\":0,\"kind\":\"NodePort\",\"name\":\"8080tcp1\",\"protocol\":\"TCP\"}]]"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-server-easy-do-plus-web"}},"spec":{"containers":[{"image":"registry.cn-hangzhou.aliyuncs.com/gebilaoyu/easy-do-plus-web:latest","imagePullPolicy":"Always","name":"easy-do-plus-web","ports":[{"containerPort":8080,"name":"8080tcp1","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true,"volumeMounts":[{"mountPath":"/opt/bitnami/nginx/conf/server_blocks/","name":"vol3"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":292,"items":[{"key":"nginx.conf","path":"my_server_block.conf"}],"name":"nginx.conf","optional":false},"name":"vol3"}]}}},"status":{}}'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-web
  name: easy-do-plus-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-02T17:37:27Z"
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"easy-do-plus-web-nodeport","hostPort":0,"kind":"NodePort","name":"8080tcp300101","protocol":"TCP","sourcePort":30010}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-server-easy-do-plus-web
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/easy-do-plus:web-1.0.0
        imagePullPolicy: Always
        name: easy-do-plus-web
        ports:
        - containerPort: 8080
          name: 8080tcp300101
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/conf/server_blocks/
          name: vol3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 292
          items:
          - key: nginx.conf
            path: my_server_block.conf
          name: nginx.conf
          optional: false
        name: vol3
status: {}
