apiVersion: v1
data:
  MYSQL_HOST: mariadb
  MYSQL_PASS: 9D3NNHBdg6yNELCHJ9DpGYpewKdgPmnE
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: 9D3NNHBdg6yNELCHJ9DpGYpewKdgPmnE
  MYSQL_USER: root
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-v7bm2
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:MYSQL_HOST: {}
        f:MYSQL_PASS: {}
        f:MYSQL_PORT: {}
        f:MYSQL_ROOT_PASSWORD: {}
        f:MYSQL_USER: {}
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
    manager: Go-http-client
    operation: Update
    time: "2022-08-27T15:11:39Z"
  name: mysql
